### ISSUE TITLE
Error with ocaml.org

### ISSUE THREAD

**Issue by dinosaure** [Cumulus/Syndic#54]
I try to create a tests suites for CI but Syndic raise an error with `http://ocaml.org/feed.xml` (the only test for the moment). The bug is: `document MUST contains exactly one <channel> element`. Something is wrong in `Syndic.Atom`. I'll search the bug. We can see the tests suites in `test` branch.

PS: I have a new monitor for my computer !

**Comment by Chris00** [comment]
On Sun, 5 Apr 2015 09:18:19 -0700, Calascibetta Romain wrote:
> 
> I try to create a tests suites for CI but Syndic raise an error with http:// ocaml.org/feed.xml (the only test for the moment). The bug is: document MUST contains exactly one <channel> element. Something is wrong in Syndic.Atom. I'll search the bug.

Looks like you are tying to parse the feed with RSS2.  This test is a
good idea, I get:

Syndic_error.Error ((279, 1661),
 "Category elements MUST have a 'term' attribute").

This indeed needs to be investigated.

> PS: I have a new monitor for my computer !

Glad for you!

**Comment by Chris00** [comment]
@dinosaure I am inclined to release version 1.3.1 for the feed of the website to be correct but you may want to finish your test suite first.  Let me now.

**Comment by dinosaure** [comment]
Yes, the test suite it's not mandotary for the next release - it's just for us. So, you can release 1.3.1 now :+1: !
