### ISSUE TITLE
Atom.link title

### ISSUE THREAD

**Issue by Chris00** [Cumulus/Syndic#55]
Since a `link.title = Some ""` should not be outputted (according to the [W3 validator](http://validator.w3.org/feed/)), do we really want to make a difference between  with `link.title = None`?  Shouldn't we just declare `title: string` and consider `""` as the absence of title?

**Comment by dinosaure** [comment]
Yes, I think it's more easy to use `string` instead `string option`. And with that, we still *respect* the RFC.

**Comment by Chris00** [comment]
Did you close it because you will be working on it??

**Comment by dinosaure** [comment]
Ah, I think you already work on it, sorry.

**Comment by Chris00** [comment]
I'll try to find some time in the coming days to do it — but I wanted to make sure you agreed since it is a non backward compatible change...
