### ISSUE TITLE
TyXML

### ISSUE THREAD

**Issue by dinosaure** [Cumulus/Syndic#58]
Syndic to TyXML and TyXML to Syndic ? It's possible, but we should use a functorial approch like [Svg](https://github.com/ocsigen/tyxml/blob/master/lib/svg_sigs.mli) ? (cc @Drup)

**Comment by Drup** [comment]
Do you really manipulate html/svg as something else than a big blob of text ? It didn't seem so last I looked.

**Comment by dinosaure** [comment]
We use a simple subset of `XML` (see [Syndic_xml](https://github.com/Cumulus/Syndic/blob/master/lib/syndic_xml.ml)). From that, we convert to feed (Atom, RSS, etc.) but if the feed has a content like HTML, we convert to `Syndic_xml` for XHTML or escaped string for HTML (see [this](https://github.com/Cumulus/Syndic/blob/master/lib/syndic_atom.ml#L70) for ATOM).

**Comment by Drup** [comment]
Then I don't see what tyxml brings you. Just pass html around as a big blob. You don't need type safe composition, which is what tyxml is about.

**Comment by dinosaure** [comment]
My way is to produce a TyXML value from Syndic value for homogeneity if you want to use her in Eliom for example. So, the question is, how to convert a Syndic value to TyXML value, it's juste a: `Syndic_atom.feed -> Xml.elt` ?

**Comment by Drup** [comment]
Is there anything in the atom specification that constraints what kind of html element can be as first children ? If not, yes, you can't do better. Note that you should not produce `Xml.elt`, since Tyxml is functorized over that, and all the various implement (eliom, jsoo, the literal one in tyxml) are different. So you need to make a functor too.

**Comment by dinosaure** [comment]
After discussion, we need an HTML5 parser for a practical use of Syndic to Tyxml converter. I hope we will have this parser. Meanwhile, I keep this issue.

**Comment by Chris00** [comment]
Yes, a robust HTML5 parser would be nice!  :+1:

**Comment by dinosaure** [comment]
Maybe [aantron/markup.ml](https://github.com/aantron/markup.ml) ?

**Comment by dinosaure** [comment]
I think, the best way for Syndic it's to do nothing about HTML 5 Document and let the user to compute the data (with markup.ml, sounds good).
