### ISSUE TITLE
Cannot match text_construct (constructor name collision with content)

### ISSUE THREAD

**Issue by brabalan** [Cumulus/Syndic#67]
I'm trying to match a `Syndic_atom.text_construct` but the `Text` constructor is shadowed by the content type: 
- https://github.com/Cumulus/Syndic/blob/master/lib/syndic_atom.mli#L11
- https://github.com/Cumulus/Syndic/blob/master/lib/syndic_atom.mli#L346

Is this a bug?

**Comment by brabalan** [comment]
I realize that I can get around this by using type annotations, but it's not very convenient.

**Comment by dinosaure** [comment]
It's a problem indeed - it's not usefull. But I don't know about a different name for this constructor :( . If you have an idea :) ?

**Comment by brabalan** [comment]
You could prefix all the `text_construct` constructors with `TC`.

**Comment by Chris00** [comment]
Another possibility would be to define a `Text_construct` sub-module (which can be shortened to `TC` by a module alias or locally opened).  Eventually some convenience functions could be added to that module (e.g. `to_html`).

**Comment by Chris00** [comment]
@brabalan Note that Syndic makes use of type directed disambiguation elsewhere; for example `uri` is used as a field in several records.  I do not think we should get rid of all of them.

**Comment by brabalan** [comment]
@Chris00 I agree. Maybe a good workaround could be a comment in the mli file showing how to use these constructors (i.e., by adding type annotations).

**Comment by dinosaure** [comment]
You can see #70
