### ISSUE TITLE
Not_Found on Atom feed with a <content/>

### ISSUE THREAD

**Issue by mro** [Cumulus/Syndic#83]
Syndic version: 1.6.1

While content *should* have a value, the W3C validator issues a warning only but considers the feed still to be valid.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fl.mro.name%2Fo%2Fp-1%2F

Would you consider/accept a patch relaxing the parsing here?

**Comment by dinosaure** [comment]
Sorry for my late but can I re-open this issue to still be able to track it into my _todo_ list?

**Comment by mro** [comment]
sure, I am just purging my github legacy and close all my stale issues.
